# Generated by Django 6.1 on 2026-08-22 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=150)),
                ('date', models.CharField(blank=True, max_length=30)),
                ('credential_url', models.URLField(blank=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=150)),
                ('start_year', models.CharField(max_length=10)),
                ('end_year', models.CharField(max_length=10)),
                ('score_label', models.CharField(help_text='e.g. CGPA or Percentage', max_length=40)),
                ('score_value', models.CharField(help_text='e.g. 8.5 or 87%', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120)),
                ('organization', models.CharField(max_length=120)),
                ('track', models.CharField(choices=[('se', 'Software Engineer'), ('da', 'Data Analyst'), ('both', 'Both')], default='both', max_length=6)),
                ('start_date', models.CharField(help_text='e.g. Jan 2025', max_length=30)),
                ('end_date', models.CharField(default='Present', max_length=30)),
                ('responsibilities', models.TextField(help_text='One point per line.')),
                ('technologies', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('track', models.CharField(choices=[('se', 'Software Engineer'), ('da', 'Data Analyst'), ('both', 'Both')], default='both', max_length=6)),
                ('category', models.CharField(choices=[('django', 'Django / Web'), ('python', 'Python'), ('data', 'Data Analysis'), ('ml', 'Machine Learning'), ('bi', 'Business Intelligence')], default='django', max_length=10)),
                ('short_description', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('problem_statement', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='One feature per line.')),
                ('challenges', models.TextField(blank=True)),
                ('solutions', models.TextField(blank=True)),
                ('technologies', models.CharField(help_text='Comma-separated, e.g. Python, Django, SQLite', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('metric_label', models.CharField(blank=True, help_text="e.g. 'Accuracy' or 'Records analyzed'", max_length=60)),
                ('metric_value', models.CharField(blank=True, help_text="e.g. '89.1%'", max_length=60)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateField()),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Adabala Satya Sai', max_length=120)),
                ('location', models.CharField(default='Razole, Andhra Pradesh, India', max_length=120)),
                ('email', models.EmailField(default='saiadabala53@gmail.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='+91 8008968188', max_length=30)),
                ('github_url', models.URLField(default='https://github.com/Satyasai-Adabala')),
                ('linkedin_url', models.URLField(default='https://linkedin.com/in/satya-sai-adabala-333687286')),
                ('tagline_se', models.CharField(default='Python & Django Developer building things that ship.', max_length=200)),
                ('tagline_da', models.CharField(default='Data Analyst turning raw numbers into decisions.', max_length=200)),
                ('summary', models.TextField(default='Fresher engineering graduate who builds real, working software instead of tutorial clones - a live Django e-commerce platform, four end-to-end data projects, and a habit of shipping rather than just learning.')),
                ('resume_se', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('resume_da', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('projects_completed', models.PositiveIntegerField(default=5)),
                ('technologies_count', models.PositiveIntegerField(default=18)),
                ('internships_count', models.PositiveIntegerField(default=2)),
                ('certifications_count', models.PositiveIntegerField(default=4)),
            ],
            options={
                'verbose_name': 'Site Profile',
                'verbose_name_plural': 'Site Profile',
            },
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('track', models.CharField(choices=[('se', 'Software Engineer'), ('da', 'Data Analyst'), ('both', 'Both')], default='both', max_length=6)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('proficiency', models.PositiveIntegerField(default=70, help_text='0-100, keep it honest.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.skillgroup')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
